### ISSUE TITLE
Multiple paragraph text error.

### ISSUE THREAD

**Issue by gledos** [sondregronas/mkdocs-callouts#1]
This is a great plugin, but I'm having a little problem with the following:

```markdown
> [!quote]+ test 1
> test 2
>
> test 3
```

Obsidian:

![圖片](https://user-images.githubusercontent.com/23720620/173308816-ad1cbeb5-c89e-4a1f-bf1f-275aa80be613.png)

MkDocs:

![圖片](https://user-images.githubusercontent.com/23720620/173308885-e89295b1-c380-41b5-9e93-fcae0393543e.png)

**Comment by sondregronas** [comment]
Good catch, thanks 👍 

Should be resolved in latest release
