### ISSUE TITLE
Nested in block(s)

### ISSUE THREAD

**Issue by Nealium** [sondregronas/mkdocs-callouts#15]
I have a block like:

```markdown
# Settings

> File: `settings.py`
> Function: `dothing`
>
> ```python
> settings = {
>     log_file: "logs.log",
>     log: True,
>     a: None,
>     b: None,
> }
> ```
>
> > !!! Note "Note: `a`"
> >     If `a` is `True` then `b` must be `False`
> >
> > !!! Note "Note: `a` and `b`"
> >     Both `a` and `b` don't do anything
```

When transfered to 
```markdown
> > > [!note] Note: `a`
> > > If `a` is `True` then `b` must be `False`
> >
> > > [!note] Note: `a` and `b`
> > > Both `a` and `b` don't do anything
```
It is just being rendered as raw text in a block.

While this is a somewhat extreme example, even a single nested block cannot have a callout from what I've tested.

**Comment by sondregronas** [comment]
Hi! Thanks for catching this - I was unaware that mkdocs would render callouts inside blockquotes and therefore never considered this.

I created a branch that can be installed via 

```bash
pip install git+https://github.com/sondregronas/mkdocs-callouts@feature/blockquote-support
```

I will need to do some more testing, but afaik it should work fine without breaking anything. Please test it and let me know if you encounter any issues.

I'll update the main branch after doing some testing on my own - it's a relatively significant change, and while the unit tests pass it might have some weird consequences that the tests don't cover.

**Comment by sondregronas** [comment]
@Nealium - Blockquotes should now work in the latest 1.14.0 release, please let me know if you encounter issues with it 😄 

Example page: https://sondregronas.github.io/mkdocs-callouts/Tests/blockquotes/tricky%20blockquote/

**Comment by Nealium** [comment]
You're quick! Works great, you absolutely nailed it! Thanks a lot
