### ISSUE TITLE
Obsidian vs mkdocs Admonition Titles

### ISSUE THREAD

**Issue by FurretGoWalcc** [sondregronas/mkdocs-callouts#4]
Thanks for the save! I wrote most of my notes within admonitions in Obsidian, so seeing that the syntax was different for mkdocs was a scary moment. 
Obsidian aliases several of the admonition 'titles', e.g. a [!tip] is equivalent to [!hint]. In Material for Mkdocs, these aliases no longer exist, so the admonition falls back to the [!note] theming. It would be handy for those with many notes to have this tool replace the aliases listed on [Obsidian](https://help.obsidian.md/How+to/Use+callouts) for the [mkdocs equivilents](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#collapsible-blocks).
E.g.
`>[!summary] -> !!! abstract`

**Comment by sondregronas** [comment]
Thank you for the suggestion, I'll look into adding this as an optional (but enabled by default) feature shortly 👍

**Comment by sondregronas** [comment]
This has now been shipped with version `1.9.0`, please let me know if you encounter any issues with the release!

Interestingly enough this behavior was just [recently removed](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#fn:1) (3 weeks ago!) from mkdocs-material 😄 

The behavior can be disabled by setting `aliases` to `false` in the plugin configuration:
```yaml
plugins:
  - search
  - callouts:
      aliases: false
```
