### ISSUE TITLE
`pkg_resources` is deprecated

### ISSUE THREAD

**Issue by sosiristseng** [sondregronas/mkdocs-callouts#5]
I got the message: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

This warning is also present in CI: https://github.com/sondregronas/mkdocs-callouts/actions/runs/6535616569/job/17745477821#step:5:88

**Comment by sondregronas** [comment]
Should be fixed now, thanks for pointing that out 👍
