### ISSUE TITLE
Can't handle nested callouts?

### ISSUE THREAD

**Issue by ryran** [sondregronas/mkdocs-callouts#7]
Is there a way to get this to handle nested callouts? (See attached image.)

![nested](https://github.com/sondregronas/mkdocs-callouts/assets/1092618/af7954d2-9e11-4bed-bbd4-ec9875c07118)

Or perhaps that's an issue with the admonitions plugin?

**Comment by sondregronas** [comment]
I'll have a look into it - nested callouts should be supported but the syntax isn't that lenient

This syntax should work

```
> [!info]
>> [!info]
```

Whereas this won't, though it probably should:
```
> [!info]
> > [!info]
```

I'll try to have a fix ready soon enough 🙂

**Comment by ryran** [comment]
Ohhhhhh wow I didn't even think to try that! You're right. That fixed it. :smile: 

I also notice that lists inside a callout don't seem to work, e.g.:
```
> [!info]
> Text here
> - list item
> - another list item
```
In that example, the hyphens are displayed inside the callout as-is -- not as bullet points and not with indentation. Any ideas for a work-around?

**Comment by sondregronas** [comment]
That's just markdown syntax being a little weird, these will work:

```
> [!info]
> Text here
>
> - list item
> - another list item

> [!info]
> - list item
> - another list item
```

It would technically be possible to automatically add an empty line before every list, which might be a good idea to do given that Obsidian does this. I'll make this an option when I can find the time

**Comment by ryran** [comment]
Ahhhhhhh I see. Thank you.

**Comment by sondregronas** [comment]
I've implemented the syntax for nested callouts to support whitespace after the `>` symbols - this should now work in 1.11.0

I'll need some time to think about how to implement breakless lists within callouts before I merge the PR (#8)

**Comment by sondregronas** [comment]
Should work now in the latest release - thanks for the suggestion, been meaning to get around to this 😄

**Comment by ryran** [comment]
Thanks! Awesome!

**Comment by ryran** [comment]
FYI: I think the breakless_lists fix is too over-eager. Here are some examples of it messing with things that it shouldn't.

Added a blank newline after the `_italic_` line:
![a](https://github.com/sondregronas/mkdocs-callouts/assets/1092618/04865bf3-049a-4441-8403-b8ee83cc1424)

Added blank newlines after first line of tables, breaking them:
![c](https://github.com/sondregronas/mkdocs-callouts/assets/1092618/d3e217a1-08be-4952-886f-e16e72dda1d8)

Obviously, you had the foresight to provide that `breakless_lists: false` option, so using that fixes it. :slightly_smiling_face: Just thought I'd share.

**Comment by sondregronas** [comment]
Strange - I thought I specifically put in a space character at the end of the regex to prevent this behavior, as `* this` is a list item but `*this*` or `*:..` obviously isn't. I'll have to double check and get this sorted.

Thanks for your thorough testing and support, it's been helpful 🙂

**Comment by ryran** [comment]
> Thanks for your thorough testing and support, it's been helpful 🙂

You're welcome! Tho it hasn't been that thorough.

> I also see I enabled the breakless list handler outside of the callout block scope, rookie mistake on my part.

Yeah I noticed that too but figured it was intentional since this was about compat with Obsidian
